In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
2.0.2


In [8]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [16]:

#0-D arrays
arr=np.array(42)
print(arr)
#1-D array
arr=np.array([1,2,3,4,5])
print(arr)
#2-D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
#3-D array
arr=np.array([[[1,2,3],[4,5,6],]])
print(arr)


42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]


In [19]:
#no of dimensions
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)


0
1
3


In [24]:
#Higher Dimensional Arrays
import numpy as np
arr = np.array([1,2,3,4],ndmin=6)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions: 6


In [27]:
#numpy array Indexing
arr=np.array([1,2,3,4])
print(arr[2])
print(arr[0]+arr[2])

3
4


In [30]:
#Accesing 2-D arrays
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',arr[0,1])



2nd element on 1st row: 2


In [31]:
#Third element of the second array of the first array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [33]:
#negative indexing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Las element fron 2nd dim:",arr[0,-1])

Las element fron 2nd dim: 5


In [39]:
#array slicing
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
#slicing 2-D arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[7 8 9]
[3 8]


In [ ]:
#Numpy data types